apiVersion : apps/v1
kind: Deployment
metadata:
  name: conferencesystemuser 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conferencesystemuser
  template:
    metadata:
      labels:
        app: conferencesystemuser 
    spec:
      containers:
        - name: conferencesystemuser 
          image: conferencesystem.azurecr.io/conferencesystemuser
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: usermssql
                  key: constr