apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb
spec:
  replicas: 1
  selector:
     matchLabels:
       app: userdb
  template:
    metadata:
      labels:
        app: userdb
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: userdb
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: usermssql
              key: pwd
        volumeMounts:
        - name: managmentmssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: managmentmssqldb
        persistentVolumeClaim:
          claimName: userdb-data
---
apiVersion: v1
kind: Service
metadata:
  name: userdb
spec:
  selector:
    app: userdb
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer